<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-04-12 16:40
=======
# Generated by Django 3.0.4 on 2020-04-12 19:43
>>>>>>> e8adca059b9b53ead2d8aa6a5d902129fdb7b7f2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='StudentCourses',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
=======
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
>>>>>>> e8adca059b9b53ead2d8aa6a5d902129fdb7b7f2
                ('courses', models.CharField(max_length=100)),
            ],
        ),
    ]
