# Generated by Django 3.0.3 on 2020-04-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourses',
            old_name='student',
            new_name='user',
        ),
    ]
