# Generated by Django 3.0.5 on 2020-04-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenNo', models.CharField(max_length=10)),
                ('courseID', models.CharField(max_length=10)),
            ],
        ),
    ]
