# Generated by Django 3.0.3 on 2020-04-04 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_section', '0006_auto_20200404_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
